version: "3"
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password

  back:
    build: ./back
    command: bash -c "rm -f tmp/pids/server.pid && rm -f tmp/pids/unicorn.pid && bundle exec unicorn -c config/unicorn.rb"
    volumes:
      - .:/myapp
    ports:
      - "3000"
    depends_on:
      - db
    environment:
      - EDITOR=vim

  front:
    build: ./front
  
  web:
    image: emarcs/nginx-git
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/logs:/var/log/nginx
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/ssl/server.crt:/etc/nginx/ssl/server.crt
      - ./nginx/ssl/server.key:/etc/nginx/ssl/server.key
      - ./back:/myapp