version: "3"
services:
  back:
    command: bash -c "rm -f tmp/pids/server.pid && rm -f tmp/pids/unicorn.pid && bundle exec unicorn -c config/unicorn.rb -E production"
    environment:
      - RAILS_ENV=production
      
  https-portal:
    environment:
      DOMAINS: stave-back.com -> http://web:80
      STAGE: production
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro