version: "3"
services:
  db:
    image: postgres
    volumes:
      - ./back/tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password

  back:
    build: ./back
    command: bash -c "rm -f tmp/pids/server.pid && rm -f tmp/pids/unicorn.pid && bundle exec unicorn -c config/unicorn.rb"
    volumes:
      - ./back:/back
    depends_on:
      - db
    environment:
      - EDITOR=vim

  web:
    image: emarcs/nginx-git
    ports:
      - 80:80
    volumes:
      - ./nginx/logs:/var/log/nginx
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./back:/back
      - ./front:/front