version: "3"
services:
  db:
    image: postgres
    volumes:
      - ./back/tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password

  back:
    build: ./back
    command: bash -c "rm -f tmp/pids/server.pid && rm -f tmp/pids/unicorn.pid && bundle exec unicorn -c config/unicorn.rb"
    volumes:
      - ./back:/back
    depends_on:
      - db
    environment:
      - EDITOR=vim

  web:
    image: emarcs/nginx-git
    volumes:
      - ./nginx/logs:/var/log/nginx
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/htpasswd:/srv/htpasswd
      - ./back:/back
      - ./front:/front
    depends_on:
      - back

  https-portal:
    image: steveltn/https-portal
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web
    environment:
      DOMAINS: localhost-> http://web:80
      STAGE: local
    