name: Build and Deploy to Google Compute Engine
on:
  push:
    branches: [main]

env:
  PROJECT_ID: ${{ secrets.GCE_PROJECT }}
  GCE_INSTANCE: instance-1  # TODO: update to instance name
  GCE_INSTANCE_ZONE: us-central1-a   # TODO: update to instance zone

jobs:
  build:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest

    steps:
    # Setup gcloud CLI
    - uses: google-github-actions/setup-gcloud@master
      with:
        version: '290.0.1'
        service_account_key: ${{ secrets.GCE_SA_KEY }}
        project_id: ${{ secrets.GCE_PROJECT }}

    - name: SSH
      run: |
        gcloud compute ssh $GCE_INSTANCE --zone=$GCE_INSTANCE_ZONE --command="(cd ../web && ls && git pull && git submodule update && bash -ci 'docker-compose build' && bash -ci 'docker-compose down' && bash -ci 'docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d') &"
