name: Update Submodule

on:
  repository_dispatch:
    types: [front_update]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with: 
          fetch-depth: 0
          submodules: recursive
          token: ${{secrets.STAVE_ACCESS_TOKEN}}

      - name: Update submodule
        run: |
          git submodule update --remote front
      
      - name: Commit
        run: |
          git config --local user.name "izszzz"
          git config --local user.email "izszzz@yahoo.co.jp"
          git add -A
          git status
          git commit -m "update submodule front(by update_submodule.yml)"

      - name: Push
        run: |
          git push origin develop
