name: Update Submodule

on:
  repository_dispatch:
    types: [front_update]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          ref: develop

      - name: Update
        run: |
          echo "Hello!"